name: CI/CD Pipeline - Node.js with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-static-site:latest ./Projects/ci-cd-docker-pipeline


      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-static-site:latest
